### ISSUE TITLE
DevOps - set up cronjob for letsencrypt renewal and ensure it works.

### ISSUE THREAD

**Issue by mgregoro** [MI-OSiRIS/aa_services#11]
What the title says, also oakd.osris.org and comanage.osris.org should both be on the certificate (and both should be CNAMEs for whatever the box is actually called)

**Comment by bmeekhof** [comment]
oadk.osris.org CNAME configured (comanage.osris.org already done).

Letsencrypt inclusion done in https://github.com/MI-OSiRIS/puppet/commit/20d53b37f2d9160e5a13fa5ad4e093f2fd1fdf37
