### ISSUE TITLE
Finish OAA Token Schema

### ISSUE THREAD

**Issue by mgregoro** [MI-OSiRIS/aa_services#5]
Finish OAA Token Schema and the Perl "objects" that will front them.

**Comment by bmeekhof** [comment]
Should I export this and update schema distributed to our 389 installations  (https://github.com/MI-OSiRIS/puppet-ds389/blob/master/files/schema/70osiris.ldif)  ?

**Comment by mgregoro** [comment]
No the file has been rebuilt or tested yet
